version: '3.8'
services:
  postgres:
    image: 'postgres:15.5'
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    env_file: .env
    ports:
      - ${PG_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DBNAME}" ]
      interval: 1s
      timeout: 10s
      retries: 60
    restart: always
    extra_hosts:
      - "localhost:host-gateway"
  flask:
    build: .
    command: python -m gunicorn --bind=0.0.0.0:${FLASK_PORT} app:app -w=4
    env_file: .env
    environment:
      - DEBUG_MODE=false
    ports:
      - ${FLASK_PORT}:5000
    stop_signal: SIGINT
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "localhost:host-gateway"