services:
  postgres:
    image: 'postgres:15.5'
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DBNAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DBNAME}" ]
      interval: 1s
      timeout: 10s
      retries: 60
    restart: always
    networks:
      - my_network
    extra_hosts:
      - "localhost:host-gateway"
  flask:
    build: .
    command: python -m gunicorn --bind=0.0.0.0:${FLASK_PORT} app:app -w=4
    env_file: .env
    environment:
      - DEBUG_MODE=false
      - SERVER_HOST=0.0.0.0
    ports:
      - ${FLASK_PORT}:5000
    stop_signal: SIGINT
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_network
    extra_hosts:
      - "localhost:host-gateway"
networks:
  my_network: