name: Main test
on: [push]
jobs:
  linter:
      name: Linter
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Dependencies installation
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.1.0 wemake-python-styleguide==0.18.0 bandit==1.7.5
      - name: Flake8
        run: flake8
  tests:
    name: Tests pages
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 7930
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: change_me
          POSTGRES_DBNAME: http-server-hw
        ports:
        - 7930:5432
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
        pip install -r requirements.txt
    - name: Run tests
      run: python3 app.py & pytest test_pages.py